//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GreenMindedEntities : DbContext
    {
        public GreenMindedEntities()
            : base("name=GreenMindedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<answers> answers { get; set; }
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<questions> questions { get; set; }
        public virtual DbSet<stations> stations { get; set; }
    
        public virtual ObjectResult<SPI_Answer_Result> SPI_Answer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPI_Answer_Result>("SPI_Answer");
        }
    
        public virtual ObjectResult<SPI_Client_Result> SPI_Client()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPI_Client_Result>("SPI_Client");
        }
    
        public virtual ObjectResult<SPI_Question_Result> SPI_Question()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPI_Question_Result>("SPI_Question");
        }
    
        public virtual ObjectResult<SPI_QuestionAnswer_Result> SPI_QuestionAnswer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPI_QuestionAnswer_Result>("SPI_QuestionAnswer");
        }
    
        public virtual ObjectResult<SPI_Station_Result> SPI_Station()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPI_Station_Result>("SPI_Station");
        }
    }
}
